### ISSUE TITLE
EnnexOS first day of month

### ISSUE THREAD

**Issue by solderq35** [OSU-Sustainability-Office/automated-jobs#26]
Our webscraper only gets data from yesterday, as today's data is still in progress, so to speak.

However, on the first day of the month this bugs out; we need to detect when it is the first day of the month and select the previous month menu in the EnnexOS webscraper if so.

Remember to set headless to `false` for debug and to see what's happening when doing initial testing - https://github.com/OSU-Sustainability-Office/automated-jobs/blob/main/ennex-os/readEnnex.js#L17

You can manually change the date we're comparing against here for testing: https://github.com/OSU-Sustainability-Office/automated-jobs/blob/main/ennex-os/readEnnex.js#L89

Potentially useful for getting Month current mat-option ID: https://github.com/OSU-Sustainability-Office/automated-jobs/blob/pacific-power/PacificPower/readPP.js#L217

- [.env file](https://drive.google.com/file/d/1xX5hvh9tQLZU_s5-nvTUjpOcA6UTeDU_/view?usp=sharing)

**Comment by s-egge** [comment]
Issue has been fixed in this pull request: https://github.com/OSU-Sustainability-Office/automated-jobs/pull/31
