### ISSUE TITLE
Unix timestamp issue

### ISSUE THREAD

**Issue by solderq35** [OSU-Sustainability-Office/automated-jobs#32]
Applies to:
- SEC
- EnnexOS

Reference:
- https://playcode.io/1662076
- https://www.unixtimestamp.com/index.php

I found that if you run `readEnnex.js` or `readSEC.js` after 4PM Pacific (we are currently not on daylight savings), the unix timestamp shows a different day than if you ran the code before 4 PM Pacific.

The Energy Dashboard seems to expect the timestamps in GMT-0 timezone, leading to the "rounding errors" so to speak.

The issue can be fixed by adding the line `dateObj.setHours(2,0,0)` right after originally defining `dateObj`, as shown in the playcode above (set the time to 2:00 AM in local timezone, Pacific in this case)

Set it to 2AM instead of 12 AM just in case of daylight savings shenanigans.

Also note that the Energy Dashboard just sets a flat 7 hour offset to convert from GMT-0 to PST - https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/block.module.js#L259

So if you go to [this Energy Dashboard building for instance](https://dashboard.sustainability.oregonstate.edu/#/building/42/2), you will notice the timestamp jumps from 11:59 PM to 10:59 PM after November 5 (daylight savings).

For the solar panels this isn't a big deal at the moment, it is more important we ensure there is one data point uploaded per day, which setting the "Pacific" time to 2AM would accomplish.

**Comment by s-egge** [comment]
Fixed issue in this pull request: https://github.com/OSU-Sustainability-Office/automated-jobs/pull/33
