### ISSUE TITLE
should meter_selector_num be logged in pacificpower scraper?

### ISSUE THREAD

**Issue by solderq35** [OSU-Sustainability-Office/automated-jobs#52]
e.g. 
![image](https://github.com/OSU-Sustainability-Office/automated-jobs/assets/82061589/00b75ac5-5033-4b6c-add6-f98d521ff49a)

The intent of logging meter_selector_num was to make it easier for debugging, e.g. if meter ID `78236363` has an error, and you know the meter_selector_num values run from 0 to 106, then a meter_selector_num of `50` will let you know to search roughly the middle of the logs.

However, I think it is convenient enough to just search by the meter ID value itself (e.g. `78236363`). If debugging locally, remember to use `node readPP.js > logs/something.txt` for easy searching

**Comment by s-egge** [comment]
I think it's probably fine to leave this as is. It's logged out in a few places and since it's a smaller number, is easier to see at a glance when logic for one meter starts/ends (comparing if there are three `49`s in a row vs three of `78236363` in a row for example).
